
version: '3.9'

services:
  db:
    image: postgres:17
    container_name: ems-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lolkas228
      POSTGRES_DB: ems_backend
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ems_backend"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: ems-backend-app
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ems_backend
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      db:
        condition: service_healthy
